In [3]:
import torch
tensor = torch.rand(3,4, dtype= )

In [14]:
a = tensor

In [15]:
mlp = torch.nn.Sequential( torch.nn.Linear(4, 3), torch.nn.ReLU(), torch.nn.Linear(3, 1) )


In [16]:
mlp

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)

In [17]:
a = torch.nn.Linear(4, 3)

In [86]:
import torch
import torch.nn as nn

# Simple perceptron
class SimplePerceptron(nn.Module):
    def __init__(self, input_size):
        super(SimplePerceptron, self).__init__()
        self.linear = nn.Linear(input_size, 1)

    def forward(self, x):
        output = self.linear(x)
        return torch.sigmoid(output)

# Usage
input_size = 2  # Number of input features

# Initialize the model
model = SimplePerceptron(input_size)

# Example input (two features)
x = torch.tensor([1.0, 1.0])

# Get the output (prediction)
output = model(x)

# Print the output
print("Output:", output.item())


In [88]:
model(torch.tensor([1.0, 1.0]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [74]:
model(torch.tensor([1.0, 1.0]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)

In [44]:
model.linear.weight

Parameter containing:
tensor([[1., 1.]], requires_grad=True)

In [29]:
type(tensor)

torch.Tensor

In [125]:
import torch
import torch.nn as nn
import torch.optim as optim

# Simple perceptron
class SimplePerceptron(nn.Module):
    def __init__(self, input_size, out_size):
        super(SimplePerceptron, self).__init__()
        self.linear =  nn.Linear(input_size, out_size)

    def forward(self, x):
        output = self.linear(x)
        return torch.sigmoid(output)

# Set random seed for reproducibility
torch.manual_seed(42)

input_size = 5
out_size = 3
learning_rate = 1
epochs = 10000

# Generate random data for training
X = torch.rand(input_size)
y = X[: out_size]
#y_onehot = torch.zeros(size, 2).scatter_(1, y.unsqueeze(1), 1)

# Model parameters
print(f" shape of X: {X.shape}, shape of y: {y.shape}")

# Initialize the model, loss function, and optimizer
model = SimplePerceptron(input_size, out_size)
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# Train the model
for epoch in range(epochs):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss for this epoch
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')


 shape of X: torch.Size([5]), shape of y: torch.Size([3])
tensor([0.3034], grad_fn=<SigmoidBackward0>) tensor([0.8823, 0.9150, 0.3829])


In [126]:
y

tensor([0.8823, 0.9150, 0.3829])

In [127]:
X

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])

In [128]:
model(X)

tensor([0.5062, 0.6538, 0.4869], grad_fn=<SigmoidBackward0>)

In [160]:
import torch
import torch.nn as nn
import torch.optim as optim

def helps(x):
    return (x**2 + 2**x + 1/x)

class SimplePerceptron(nn.Module):
    def __init__(self, input_size, out_size, hidden_size):
        super(SimplePerceptron, self).__init__()
        self.linear = nn.Linear(input_size, hidden_size)
        self.layer_1 = nn.Linear(hidden_size, hidden_size)
        self.output_layer = nn.Linear(hidden_size, out_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.linear(x)
        x = self.relu(x)
        x = self.layer_1(x)
        x = self.relu(x)
        x = self.output_layer(x)
        return x

torch.manual_seed(42)

input_size = 1
out_size = 1
hidden_size = 64
learning_rate = 0.001
epochs = 10000
dataset_size = 100

X = torch.rand(dataset_size, input_size)
y = helps(X)

print(f"shape of X: {X.shape}, shape of y: {y.shape}")

model = SimplePerceptron(input_size, out_size, hidden_size)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    total_loss = 0.0
    for i in range(dataset_size):
        inputs = X[i, :]
        labels = y[i].unsqueeze(0)

        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()

    loss_now = total_loss/dataset_size
    if loss_now < 0.005:
        break

    # Print the average loss for this epoch
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {total_loss/dataset_size:.4f}')


shape of X: torch.Size([100, 1]), shape of y: torch.Size([100, 1])
Epoch [1/10000], Loss: 1312.6780
Epoch [2/10000], Loss: 1278.6072
Epoch [3/10000], Loss: 1250.1503
Epoch [4/10000], Loss: 1222.4148
Epoch [5/10000], Loss: 1189.6452
Epoch [6/10000], Loss: 1153.5596
Epoch [7/10000], Loss: 1119.8865
Epoch [8/10000], Loss: 1088.2989
Epoch [9/10000], Loss: 1057.6030
Epoch [10/10000], Loss: 1025.9015
Epoch [11/10000], Loss: 993.2218
Epoch [12/10000], Loss: 958.0746
Epoch [13/10000], Loss: 923.4249
Epoch [14/10000], Loss: 889.7601
Epoch [15/10000], Loss: 857.1247
Epoch [16/10000], Loss: 825.2771
Epoch [17/10000], Loss: 794.9078
Epoch [18/10000], Loss: 765.2355
Epoch [19/10000], Loss: 736.8620
Epoch [20/10000], Loss: 709.2207
Epoch [21/10000], Loss: 682.7543
Epoch [22/10000], Loss: 657.9791
Epoch [23/10000], Loss: 633.8425
Epoch [24/10000], Loss: 609.9400
Epoch [25/10000], Loss: 588.1955
Epoch [26/10000], Loss: 566.3603
Epoch [27/10000], Loss: 545.9485
Epoch [28/10000], Loss: 526.5192
Epoch [2

KeyboardInterrupt: 

In [147]:
X[1, :]

tensor([0.9150])

In [153]:
model(torch.tensor([0.5]))[1,:]

IndexError: too many indices for tensor of dimension 1