In [11]:
from torchvision.datasets import MNIST

mnist = MNIST(root='data', download=True)




In [35]:
mnist.targets


torch.Size([60000])

In [30]:
mnist.data.shape

torch.Size([60000, 28, 28])

In [7]:
import torch


class MLP(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.linear1 = torch.nn.Linear(input_size, hidden_size)
        self.linear2 = torch.nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.linear1(x)
        x = torch.nn.functional.relu(x)
        x = self.linear2(x)
        return x

input_size = 784
hidden_size = 128
output_size = 10

x = mnist.data.reshape(784)
model = MLP(input_size, hidden_size, output_size)

y = mnist.targets


output = model(input)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [15]:
import torch
random_input = torch.randn(5)

In [21]:
random_input.reshape(5)

tensor([-1.0456, -0.5487,  2.5413,  0.4562, -0.0144])

In [16]:
random_input

tensor([-1.0456, -0.5487,  2.5413,  0.4562, -0.0144])

In [46]:
def helps(x):
    return 1

test_tensor = torch.randn(5,5)

y = test_tensor.apply_(helps)


In [43]:
y

tensor([1., 1., 1., 1., 1.])

In [47]:
y.shape

torch.Size([5, 5])