In [68]:
import torch
import torch.nn.functional as F

In [3]:
a = [i for i in range()]

In [7]:
F.one_hot(torch.tensor([1]),50 )

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0]])

In [11]:
a = torch.rand(5)
a[-2:]

tensor([0.8562, 0.3878])

In [10]:
a

tensor([0.1675, 0.9535, 0.4283, 0.4480, 0.1068])

In [15]:
a = 5

1

In [25]:
torch.ones(2,2)

<function Tensor.type>

In [16]:
a = torch.randint(0, 100, (4,))

In [17]:
for i in a:
    print(i)

tensor(5)
tensor(89)
tensor(25)
tensor(16)


In [8]:
a = torch.nn.Embedding(2, 4)

In [3]:
a.weight.data

tensor([[-0.0814, -0.0782, -0.2089,  0.7043],
        [ 0.3737,  0.7720,  1.2135, -0.7544]])

In [4]:
a(torch.tensor([1]))

tensor([[ 0.3737,  0.7720,  1.2135, -0.7544]], grad_fn=<EmbeddingBackward0>)

In [15]:

weight = a.weight.data
torch.fft.fft(weight, dim= 1)

tensor([[-0.7955+0.0000j, -1.7991-0.9850j, -0.0269+0.0000j, -1.7991+0.9850j],
        [-0.5374+0.0000j,  3.6832-0.5162j,  2.4251+0.0000j,  3.6832+0.5162j]])

In [69]:
seq = torch.tensor([1,2,3,1,2,3,1,2,3])
f = torch.fft.fft(seq)


In [70]:
f

tensor([18.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -4.5000+2.5981j,
         0.0000+0.0000j,  0.0000-0.0000j, -4.5000-2.5981j,  0.0000-0.0000j,
         0.0000-0.0000j])

In [67]:
import plotly.graph_objects as go
seq = torch.range(0,10)
f = torch.fft.fft(seq, dim= 0)

magnitudes = torch.abs(f).numpy()
# Compute magnitudes

# Only consider the first N/2 + 1 magnitudes
half_n = len(seq) // 2 + 1
magnitudes = magnitudes[:half_n]

# Plotting
fig = go.Figure()

# Line plot for the original sequence
# fig.add_trace(go.Scatter(y=seq.numpy(), mode='lines+markers', name='Original Sequence'))

# Histogram for FFT magnitudes
fig.add_trace(go.Bar(x=list(range(1, len(magnitudes))), y=magnitudes, name='FFT Magnitudes'))

fig.show()

/var/folders/_j/ctxbrk0926zg7z8n7jc3xpp00000gn/T/ipykernel_46947/2081326806.py:2: UserWarning:

torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).



In [38]:
f.shape

torch.Size([100, 100])

In [54]:
a = torch.tensor([[1,2,3],[4,5,6], [1,7,3], [4,2,6], [1,5,3], [4,7,6]])

In [55]:
f = torch.fft.fft(a,dim= 0)

In [59]:
f

tensor([[ 1.5000e+01+0.0000e+00j,  2.8000e+01+0.0000e+00j,
          2.7000e+01+0.0000e+00j],
        [ 0.0000e+00+0.0000e+00j, -2.3842e-07-1.1921e-07j,
          0.0000e+00+0.0000e+00j],
        [ 0.0000e+00+0.0000e+00j, -8.0000e+00+3.4641e+00j,
          0.0000e+00+0.0000e+00j],
        [-9.0000e+00+0.0000e+00j,  0.0000e+00+0.0000e+00j,
         -9.0000e+00+0.0000e+00j],
        [ 0.0000e+00-0.0000e+00j, -8.0000e+00-3.4641e+00j,
          0.0000e+00-0.0000e+00j],
        [ 0.0000e+00-0.0000e+00j, -2.3842e-07+1.1921e-07j,
          0.0000e+00-0.0000e+00j]])

In [62]:
torch.norm(f[2]).item()

8.717798233032227