In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [9]:
q = torch.zeros(2,3,1)
k = torch.zeros(2,3,1)

In [10]:
attn = (k@torch.transpose(q,1,2))

lower_triangular_matrix = torch.tensor([[1 if i<=j else -torch.inf for i in range(3)] for j in range(3)]).float()

print(attn.shape)
print(attn)
print(lower_triangular_matrix)

attn = attn*lower_triangular_matrix

print(attn.shape)
print(attn)


torch.Size([2, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[1., -inf, -inf],
        [1., 1., -inf],
        [1., 1., 1.]])
torch.Size([2, 3, 3])
tensor([[[0., nan, nan],
         [0., 0., nan],
         [0., 0., 0.]],

        [[0., nan, nan],
         [0., 0., nan],
         [0., 0., 0.]]])


In [182]:
torch.softmax(attn,1)

tensor([[[0.1429, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.5000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.5000, 1.0000]],

        [[0.1429, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.0000, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.0000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.5000, 0.0000],
         [0.1429, 0.1667, 0.2000, 0.2500, 0.3333, 0.5000, 1.0000]],

        [[0.1429, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 

tensor([[[ 2.2521,    -inf,    -inf,    -inf,    -inf,     inf,     inf],
         [-0.6106,  0.5693,     inf,     inf,     inf,    -inf,    -inf],
         [-0.8011,  0.7469,  0.6339,     inf,     inf,    -inf,    -inf],
         [ 0.5171, -0.4821, -0.4092, -0.5254,    -inf,     inf,     inf],
         [ 0.7316, -0.6821, -0.5790, -0.7434, -0.6784,     inf,     inf],
         [-0.0924,  0.0861,  0.0731,  0.0938,  0.0856, -0.0255,    -inf],
         [-0.4257,  0.3969,  0.3369,  0.4325,  0.3947, -0.1176, -0.5969]],

        [[-1.7433,     inf,     inf,     inf,    -inf,    -inf,     inf],
         [-3.8335,  1.5204,     inf,     inf,    -inf,    -inf,     inf],
         [-2.1481,  0.8520,  0.6351,     inf,    -inf,    -inf,     inf],
         [ 3.4739, -1.3778, -1.0270, -1.0925,     inf,     inf,    -inf],
         [-4.3181,  1.7126,  1.2766,  1.3580, -1.1250,    -inf,     inf],
         [ 1.0926, -0.4333, -0.3230, -0.3436,  0.2847,  0.1740,    -inf],
         [-2.1320,  0.8456,  0.6303,

In [181]:
attn.shape

torch.Size([5, 7, 7])

In [37]:
X = full_data[:3,:-1]
Y =  full_data[:3,1:]

In [38]:
X,Y

(tensor([[18, 47, 56, 57, 58,  1, 15],
         [58, 47, 64, 43, 52, 10,  0],
         [43, 44, 53, 56, 43,  1, 61]]),
 tensor([[47, 56, 57, 58,  1, 15, 47],
         [47, 64, 43, 52, 10,  0, 14],
         [44, 53, 56, 43,  1, 61, 43]]))

In [157]:
a = torch.rand(5)

In [158]:
a

tensor([0.2809, 0.6480, 0.3954, 0.8794, 0.7522])

In [160]:
a/2

tensor([0.1404, 0.3240, 0.1977, 0.4397, 0.3761])

nan

In [12]:
attention = torch.rand(5,5)

In [13]:
attention

tensor([[0.6556, 0.7176, 0.8227, 0.9819, 0.7202],
        [0.3018, 0.1666, 0.5159, 0.9944, 0.4530],
        [0.3954, 0.2255, 0.2482, 0.5193, 0.8585],
        [0.4330, 0.5895, 0.7918, 0.5467, 0.3158],
        [0.0629, 0.3269, 0.1795, 0.3606, 0.6414]])

In [14]:
attention = torch.tril(attention, out = )

In [15]:
attention

tensor([[0.6556, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3018, 0.1666, 0.0000, 0.0000, 0.0000],
        [0.3954, 0.2255, 0.2482, 0.0000, 0.0000],
        [0.4330, 0.5895, 0.7918, 0.5467, 0.0000],
        [0.0629, 0.3269, 0.1795, 0.3606, 0.6414]])

In [16]:
torch.softmax(attention, 1)

tensor([[0.3250, 0.1687, 0.1687, 0.1687, 0.1687],
        [0.2444, 0.2135, 0.1807, 0.1807, 0.1807],
        [0.2467, 0.2081, 0.2129, 0.1661, 0.1661],
        [0.1862, 0.2178, 0.2666, 0.2086, 0.1208],
        [0.1525, 0.1986, 0.1714, 0.2054, 0.2720]])