In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


input_size = 2
output_size = input_size
learning_rate = 0.1
max_iters = 2500

def help(x):
    return x + 5


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(input_size, output_size, bias= False)
        self.relu = nn.ReLU()
    
    def forward(self, input, targets = None):
        logits = self.layer1(input)
        logits = self.relu(logits)
        if targets is None:
            return logits
        else:
            loss = F.mse_loss(logits, targets)
            return logits, loss

input = torch.range(1, input_size)
output = input


model = Model()


optimizer = torch.optim.SGD(model.parameters() , learning_rate)


for i in range(1, max_iters):
    logits, loss = model(input, output)
    if i%500 ==0 :
        print(f"iter:{i} loss: {loss.item()}")
        print(model.layer1.weight)
        print(logits, output)
        print("sum", torch.dot(input, model.layer1.weight[0]).item(), torch.dot(input, model.layer1.weight[1]).item())
        print()
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    






iter:500 loss: 2.0
Parameter containing:
tensor([[-0.4757,  0.7379],
        [-0.6482,  0.0763]], requires_grad=True)
tensor([1.0000, 0.0000], grad_fn=<ReluBackward0>) tensor([1., 2.])
sum 0.9999998807907104 -0.4954789876937866

iter:1000 loss: 2.0
Parameter containing:
tensor([[-0.4757,  0.7379],
        [-0.6482,  0.0763]], requires_grad=True)
tensor([1.0000, 0.0000], grad_fn=<ReluBackward0>) tensor([1., 2.])
sum 0.9999998807907104 -0.4954789876937866

iter:1500 loss: 2.0
Parameter containing:
tensor([[-0.4757,  0.7379],
        [-0.6482,  0.0763]], requires_grad=True)
tensor([1.0000, 0.0000], grad_fn=<ReluBackward0>) tensor([1., 2.])
sum 0.9999998807907104 -0.4954789876937866

iter:2000 loss: 2.0
Parameter containing:
tensor([[-0.4757,  0.7379],
        [-0.6482,  0.0763]], requires_grad=True)
tensor([1.0000, 0.0000], grad_fn=<ReluBackward0>) tensor([1., 2.])
sum 0.9999998807907104 -0.4954789876937866



/var/folders/_j/ctxbrk0926zg7z8n7jc3xpp00000gn/T/ipykernel_84927/1800754679.py:30: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  input = torch.range(1, input_size)


In [104]:
a = torch.rand(5,3)
print(a)
l = a[3]
y = a[4]

torch.dot(l,y)



tensor([[0.5855, 0.2792, 0.5563],
        [0.5337, 0.4538, 0.2945],
        [0.1201, 0.2657, 0.9471],
        [0.5789, 0.3194, 0.3005],
        [0.5955, 0.5146, 0.2507]])


tensor(0.5844)

In [77]:
model.layer1.weight

Parameter containing:
tensor([[0.7630, 0.2832],
        [0.3562, 0.5744]], requires_grad=True)

In [75]:
model.layer1.bias

Parameter containing:
tensor([0.4797, 0.3276], requires_grad=True)