In [45]:
import torch

# Example tensor with dimensions (Batch, Context Length, Model Dimension)
batch_size = 2
context_length = 3
model_dim = 4
x = torch.randn(batch_size, context_length, model_dim)
y = torch.randn(batch_size, context_length, model_dim)

def manual_layer_norm(x, epsilon=1e-5):
    # Calculate mean and variance
    mean = x.mean(dim=-1, keepdim=True)
    variance = x.var(dim=-1, keepdim=True, unbiased=False)

    # Normalize
    x_normalized = (x - mean) / torch.sqrt(variance + epsilon)

    return x_normalized

# Apply manual layer normalization
x_normalized = manual_layer_norm(x)
print(x)
print(x_normalized)


tensor([[[ 1.7222,  1.1444,  1.0009,  0.2213],
         [ 0.7229, -0.4213, -0.9725,  0.6918],
         [-0.3615, -1.3112, -0.9483,  0.7301]],

        [[ 1.8597, -0.5011, -1.3574,  1.5331],
         [-0.4577, -2.4709,  0.7182,  0.2576],
         [ 1.0488,  0.0630,  1.3145, -0.0449]]])
tensor([[[ 1.3073,  0.2282, -0.0397, -1.4958],
         [ 0.9848, -0.5853, -1.3417,  0.9422],
         [ 0.1439, -1.0851, -0.6154,  1.5566]],

        [[ 1.0916, -0.6542, -1.2875,  0.8501],
         [ 0.0250, -1.6265,  0.9897,  0.6118],
         [ 0.7621, -0.8948,  1.2086, -1.0760]]])


In [47]:
manual_layer_norm(x+y)

tensor([[[-0.9548,  1.6625, -0.5461, -0.1616],
         [ 1.3883, -1.0619, -0.8309,  0.5045],
         [-0.5273, -0.4823, -0.7158,  1.7254]],

        [[ 0.8969, -0.9272, -1.0654,  1.0957],
         [-0.8126, -1.1583,  0.8187,  1.1523],
         [ 0.6508, -0.4303,  1.1873, -1.4078]]])

In [48]:
manual_layer_norm(x) + manual_layer_norm(y)

tensor([[[-0.1845,  1.1675, -0.3716, -0.6115],
         [ 2.4756, -1.8240, -1.7927,  1.1411],
         [-0.6827,  0.3873, -0.2526,  0.5480]],

        [[ 1.0525, -2.0577, -1.2691,  2.2743],
         [-1.5259, -1.3547,  1.0364,  1.8442],
         [ 0.9857, -0.2174,  2.0003, -2.7685]]])

In [15]:
2*x

tensor([[[-4.5795,  1.5442,  0.0397,  3.8779],
         [ 3.2117,  0.9327,  1.9581, -1.6882],
         [-2.3979,  0.8282,  1.0355, -2.3568]],

        [[-0.8038,  1.8008,  1.2494, -0.2032],
         [-1.4478,  1.9009, -1.4964,  2.2762],
         [-1.0230, -3.2200, -0.1878,  1.7780]]])

In [17]:
manual_layer_norm(x)
manual_layer_norm(2*x)

tensor([[[-1.5532,  0.4283, -0.0585,  1.1835],
         [ 1.1695, -0.0948,  0.4740, -1.5487],
         [-1.0114,  0.9364,  1.0615, -0.9866]],

        [[-1.2467,  1.2234,  0.7004, -0.6771],
         [-0.9836,  0.8921, -1.0108,  1.1023],
         [-0.2007, -1.4264,  0.2652,  1.3619]]])